swagger: '2.0'
info:
  description: Flood alert API
  version: 1.0.0
  title: Flood alert API
basePath: /api
schemes:
  - http
paths:
  /alert:
    get:
      tags:
        - flood
      summary: Check alert in some place
      description: ''
      operationId: 'controllers.alert_controller.get_alerts'
      produces:
        - application/json
      parameters:
        - name: lat
          in: query
          description: Latitude
          required: false
          type: number
        - name: lon
          in: query
          description: Longitude
          required: false
          type: number
        - name: date
          in: query
          description: Date
          required: false
          type: string
          format: date
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Alert'
        '400':
          description: Invalid param values
definitions:
  Alert:
    type: object
    properties:
      date:
        type: string
        format: date
      message:
        type: string
      severity:
        type: string
        enum:
          - WARNING
          - CAUTION
          - DANGER
      latitude:
        type: number
      longitude:
        type: number
